# A single-shot build-n-pack on Alpine Linux
name: Publish Docker image
on: [push]

jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check token is set
        id: vars
        shell: bash
        run: |
            unset HAS_SECRET
            if [ -n $SECRET ]; then HAS_SECRET='true' ; fi
            echo ::set-output name=HAS_SECRET_TOKEN::${HAS_SECRET}
        env:
          SECRET: "${{ secrets.DOCKER_TOKEN }}"
      - name: Check out the repo
        uses: actions/checkout@v2
        if: ${{ steps.vars.outputs.HAS_SECRET_TOKEN }}
      - name: Convert username to lower case for docker
        id: string_user
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}
      - name: Convert repo to lower case for docker
        id: string_repo
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Set up QEMU
        if: ${{ steps.vars.outputs.HAS_SECRET_TOKEN }}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ steps.vars.outputs.HAS_SECRET_TOKEN }}
        uses: docker/setup-buildx-action@v1
      - name: Login to dockerhub
        if: ${{ steps.vars.outputs.HAS_SECRET_TOKEN }}
        uses: docker/login-action@v1
        with:
          username: ${{ steps.string_user.outputs.lowercase }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get tag name
        if: ${{ steps.vars.outputs.HAS_SECRET_TOKEN }}
        id: tags
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          debtags="${REPO_NAME}:${branch}"
          alptags="${REPO_NAME}:${branch}-alpine"
          if [ "${branch}" == "master" ]; then
            debtags="${debtags},${REPO_NAME}:latest"
            alptags="${alptags},${REPO_NAME}:latest-alpine"
          fi
          echo "::set-output name=DEBTAGS::${debtags}"
          echo "::set-output name=ALPTAGS::${alptags}"
        env:
          REPO_NAME: ${{ steps.string_repo.outputs.lowercase }}
      - name: Install toml-cli
        uses: actions-rs/install@v0.1
        with:
          crate: toml-cli
          version: latest
      - name: Get project version
        id: toml
        run: |
          NEOLINK_VERSION="$(toml get Cargo.toml  package.version | sed 's|"||g')"
          echo "::set-output name=version::${NEOLINK_VERSION}"
      - name: Push to Docker Hub Debian
        if: ${{ steps.vars.outputs.HAS_SECRET_TOKEN }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7,linux/arm/v8,linux/amd64
          push: true
          file: docker/debian/Dockerfile
          tags: ${{ steps.tags.outputs.DEBTAGS }}
          build-args: VERSION=${{ steps.toml.outputs.version }}, REPO=${{ github.repository }}, OWNER=${{ github.repository_owner }}
        env:
          DOCKER_BUILDKIT: 1
      - name: Push to Docker Hub Alpine
        if: ${{ steps.vars.outputs.HAS_SECRET_TOKEN }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          file: docker/alpine/Dockerfile
          tags: ${{ steps.tags.outputs.ALPTAGS }}
          build-args: VERSION=${{ steps.toml.outputs.version }}, REPO=${{ github.repository }}, OWNER=${{ github.repository_owner }}
